/** How well the learner appears to understand a node's concept. */
export type MasteryStatus = 'unexplored' | 'solid' | 'shaky' | 'gap'

/** `topic` nodes are learner-authored. `correction` nodes are generated by the Misconception Analyzer. */
export type NodeKind = 'topic' | 'correction'

export type Role = 'user' | 'assistant'

export interface Message {
  id: string
  role: Role
  content: string
  createdAt: number
  /** Set when the analyzer traced a misconception back to this message. */
  flaggedBy?: string
}

/**
 * Marks a thread that was held somewhere else and folded in here. The only
 * place context crosses a node boundary, so it is recorded explicitly rather
 * than silently — both to label the bubble and to keep the parent's model
 * context honest about where the exchange happened.
 */
export interface SessionOrigin {
  kind: 'correction'
  misconceptionId: string
  concept: string
  fromNodeTitle: string
}

/**
 * A single micro-chat under one node. Closed sessions collapse into an
 * accordion summary bubble on the canvas instead of scrolling forever.
 */
export interface Session {
  id: string
  title: string
  summary: string
  messages: Message[]
  createdAt: number
  closedAt?: number
  origin?: SessionOrigin
  /** True while an LLM summary is still in flight over the deterministic one. */
  summaryPending?: boolean
}

/**
 * Fading trace left where a correction node stood after its gap was closed.
 * Deliberately absent from the persisted slice: it is a moment of feedback, not
 * canvas state, so a reload clears it.
 */
export interface NodeGhost {
  id: string
  title: string
  position: { x: number; y: number }
  createdAt: number
}

export interface Misconception {
  id: string
  nodeId: string
  /** Stable rule id, e.g. `hash-always-o1`. Survives instance ids. */
  claimId: string
  /** The concept the learner tripped on, e.g. "Amortized vs worst-case cost". */
  concept: string
  /** What the learner appears to believe. */
  belief: string
  /** The accurate framing. */
  correction: string
  severity: 'high' | 'medium'
  /** Message that triggered the detection, for "jump to evidence". */
  evidenceMessageId?: string
  evidenceQuote?: string
  /** Generated sub-node that drills this gap. */
  correctionNodeId?: string
  detectedAt: number
  resolved: boolean
}

export interface NodeData extends Record<string, unknown> {
  title: string
  kind: NodeKind
  status: MasteryStatus
  /** One-line gist shown on the card face. */
  gist: string
  /** Closed micro-chats, newest last. */
  sessions: Session[]
  /** The live micro-chat. */
  active: Session
  /** Session ids currently expanded as accordion bubbles on the canvas. */
  expandedSessions: string[]
  /** Present on correction nodes: the misconception this node exists to fix. */
  fixesMisconceptionId?: string
  createdAt: number
}

export interface AnalyzerRun {
  id: string
  ranAt: number
  messagesScanned: number
  nodesScanned: number
  found: string[]
}
